[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
